# Generated by Django 4.2.30 on 2026-05-21 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('complete', 'Complete')], default='planning', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('health_score', models.IntegerField(default=50, help_text='0-100 composite project health score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('org_id', models.CharField(help_text='Clerk organisation ID', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=8)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('likelihood', models.IntegerField(choices=[(1, '1-Rare'), (2, '2-Unlikely'), (3, '3-Possible'), (4, '4-Likely'), (5, '5-Almost Certain')], default=2)),
                ('impact', models.IntegerField(choices=[(1, '1-Negligible'), (2, '2-Minor'), (3, '3-Moderate'), (4, '4-Major'), (5, '5-Catastrophic')], default=2)),
                ('mitigation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('closed', 'Closed'), ('accepted', 'Accepted')], default='open', max_length=30)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('created_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Risk',
                'ordering': ['-likelihood', '-impact'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='uc3_msme.tenant'),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('on_hold', 'On Hold')], default='not_started', max_length=30)),
                ('completion_pct', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_ai_draft', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Phase',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('payload', models.TextField(default='{}')),
                ('result', models.TextField(default='{}')),
                ('status', models.CharField(default='success', max_length=20)),
                ('ai_authority', models.CharField(blank=True, help_text='full_write | approval_required | blocked', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uc3_msme.project')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exec_logs', to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Execution Log (UC3)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('doc_type', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('superseded', 'Superseded')], default='draft', max_length=30)),
                ('is_ai_draft', models.BooleanField(default=False)),
                ('drafted_by', models.CharField(default='AI', max_length=200)),
                ('confirmed_by', models.CharField(blank=True, max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Decision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uc3_msme.project')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g. 2026-05', max_length=20)),
                ('projected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Cashflow',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('estimated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uc3_msme.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Budget Line',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('created_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uc3_msme.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Action Item',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Admin / Owner'), ('pm', 'Project Manager'), ('supervisor', 'Site Supervisor'), ('finance', 'Finance Officer'), ('readonly', 'Read-Only Viewer')], default='readonly', max_length=30)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Tenant User',
                'unique_together': {('tenant', 'email')},
            },
        ),
    ]
