# Generated by Django 4.2.30 on 2026-05-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc3_msme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.TextField(blank=True, help_text='Paste document content for AI analysis'),
        ),
        migrations.AddField(
            model_name='risk',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='escalation_note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'ordering': ['-week_ending'],
            },
        ),
        migrations.CreateModel(
            name='VariationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('scope_change', models.TextField(blank=True)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, help_text='Positive = cost increase', max_digits=12)),
                ('time_impact_days', models.IntegerField(default=0, help_text='Positive = schedule delay in days')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30)),
                ('is_ai_drafted', models.BooleanField(default=False)),
                ('submitted_by', models.CharField(blank=True, max_length=200)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Variation Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('attendees', models.CharField(blank=True, max_length=500)),
                ('raw_minutes', models.TextField()),
                ('extracted_actions', models.TextField(default='[]', help_text='JSON list of extracted action items')),
                ('actions_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('processed', 'Actions Extracted'), ('confirmed', 'Actions Confirmed')], default='raw', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_minutes', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Meeting Minutes',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text='e.g. client company name', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='uc3_msme.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Client Portal Token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('xero', 'Xero'), ('myob', 'MYOB AccountRight'), ('qbo', 'QuickBooks Online')], default='xero', max_length=20)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Sync Error')], default='disconnected', max_length=20)),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('access_token', models.TextField(blank=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_log', models.TextField(blank=True)),
                ('records_synced', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_connections', to='uc3_msme.tenant')),
            ],
            options={
                'verbose_name': 'Accounting Connection',
                'ordering': ['-created_at'],
            },
        ),
    ]
