# Generated by Django 4.2.30 on 2026-05-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc1_roofing', '0008_quote_roof_polygon'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendormaterialprice',
            name='unique_vendor_material',
        ),
        migrations.AlterField(
            model_name='pricechecklog',
            name='raw_log',
            field=models.TextField(blank=True, help_text='Detailed line-by-line log'),
        ),
        migrations.AlterField(
            model_name='pricechecklog',
            name='summary',
            field=models.TextField(blank=True, help_text='Human-readable summary of changes'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='flat_area_sqm',
            field=models.DecimalField(decimal_places=2, help_text='Flat (plan) roof area in m²', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='material',
            field=models.CharField(choices=[('colorbond', 'Colorbond Steel'), ('terracotta', 'Terracotta Tiles'), ('concrete', 'Concrete Tiles'), ('zincalume', 'Zincalume'), ('slate', 'Natural Slate'), ('asphalt', 'Asphalt Shingles')], default='colorbond', max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pitch_type',
            field=models.CharField(choices=[('flat', 'Flat 0°'), ('low', 'Low 10°'), ('standard', 'Standard 22°'), ('steep', 'Steep 35°'), ('very_steep', 'Very Steep 45°')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='waste_factor_pct',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Waste allowance %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='material',
            field=models.CharField(choices=[('colorbond', 'Colorbond Steel'), ('terracotta', 'Terracotta Tiles'), ('concrete', 'Concrete Tiles'), ('zincalume', 'Zincalume'), ('slate', 'Natural Slate'), ('asphalt', 'Asphalt Shingles')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='pitch_type',
            field=models.CharField(choices=[('flat', 'Flat 0°'), ('low', 'Low 10°'), ('standard', 'Standard 22°'), ('steep', 'Steep 35°'), ('very_steep', 'Very Steep 45°')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='rate_ex_gst',
            field=models.DecimalField(decimal_places=2, help_text='Rate per unit, excluding GST (AUD)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rooflidaranalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roofpolygon',
            name='confidence',
            field=models.CharField(blank=True, help_text='High / Medium / Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='roofpolygon',
            name='coordinates_json',
            field=models.TextField(default='[]', help_text='JSON array of [lat, lng] pairs'),
        ),
        migrations.AlterField(
            model_name='roofpolygon',
            name='detection_path',
            field=models.CharField(blank=True, help_text='e.g. Path 1 — OSM, Manual', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vendormaterialprice',
            unique_together={('vendor', 'material')},
        ),
    ]
