# Generated by Django 5.2.14 on 2026-05-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc1_roofing', '0009_remove_vendormaterialprice_unique_vendor_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, default=0, help_text='Annual %. 0 = interest-free.', max_digits=5)),
                ('min_term_months', models.IntegerField(default=12)),
                ('max_term_months', models.IntegerField(default=60)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Finance Provider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GutteringRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('gutter', 'Guttering (per linear metre)'), ('downpipe', 'Downpipe (each)'), ('fascia', 'Fascia Board (per linear metre)'), ('valley', 'Valley Iron (per linear metre)'), ('ridge_cap', 'Ridge Cap (per linear metre)')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(default='lm', max_length=20)),
                ('rate_ex_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guttering Rate',
                'ordering': ['item_type'],
            },
        ),
        migrations.CreateModel(
            name='SolarPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('referral_fee_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='% of solar install value paid as referral fee', max_digits=5)),
                ('avg_install_value', models.DecimalField(decimal_places=2, default=10000, help_text='Average system value for commission estimate', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solar Partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StormEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('hail', 'Hailstorm'), ('cyclone', 'Cyclone'), ('wind', 'Severe Wind'), ('flood', 'Flooding / Water Ingress'), ('fire', 'Ember Attack / Bushfire')], default='hail', max_length=20)),
                ('event_date', models.DateField()),
                ('severity', models.IntegerField(choices=[(1, '1 — Low'), (2, '2 — Low'), (3, '3 — Moderate'), (4, '4 — Severe'), (5, '5 — Extreme')], default=3)),
                ('affected_suburbs', models.TextField(help_text='Comma-separated list of affected suburbs')),
                ('state', models.CharField(default='QLD', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('leads_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Storm Event',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='RoofConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('report_type', models.CharField(choices=[('homebuyer', 'Pre-Purchase Inspection'), ('insurance', 'Insurance Assessment'), ('maintenance', 'Routine Maintenance Report'), ('strata', 'Strata / Body Corporate')], default='homebuyer', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('condition_grade', models.CharField(choices=[('A', 'A — Excellent (new/near-new, no action)'), ('B', 'B — Good (minor maintenance, 10+ years life)'), ('C', 'C — Fair (scheduled replacement within 5 years)'), ('D', 'D — Poor (replacement within 2 years recommended)'), ('F', 'F — Failed (immediate replacement required)')], default='B', max_length=2)),
                ('condition_score', models.IntegerField(default=70, help_text='0-100 overall score')),
                ('life_remaining_years', models.IntegerField(default=10)),
                ('urgency_level', models.CharField(choices=[('routine', 'Routine — No urgency'), ('within_5_years', 'Within 5 Years'), ('within_2_years', 'Within 2 Years'), ('within_1_year', 'Within 1 Year'), ('immediate', 'Immediate Action Required')], default='routine', max_length=20)),
                ('ai_assessment', models.TextField(blank=True)),
                ('recommended_works', models.TextField(blank=True)),
                ('inspector_name', models.CharField(blank=True, max_length=200)),
                ('price_ex_gst', models.DecimalField(decimal_places=2, default=350, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='uc1_roofing.quote')),
            ],
            options={
                'verbose_name': 'Roof Condition Report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SolarReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to Partner'), ('contacted', 'Client Contacted'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=20)),
                ('solar_potential_kwh', models.FloatField(default=0)),
                ('best_section_area', models.FloatField(default=0)),
                ('best_section_facing', models.CharField(blank=True, max_length=20)),
                ('estimated_capacity_kw', models.FloatField(default=0)),
                ('estimated_install_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_referral_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uc1_roofing.solarpartner')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_referrals', to='uc1_roofing.quote')),
            ],
            options={
                'verbose_name': 'Solar Referral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StormLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(default='QLD', max_length=10)),
                ('roof_area_sqm', models.FloatField(default=0)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('new', 'New — Not Contacted'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost / No Response')], default='new', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storm_leads', to='uc1_roofing.quote')),
                ('storm_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='uc1_roofing.stormevent')),
            ],
            options={
                'verbose_name': 'Storm Lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
