# Generated by Django 4.2.30 on 2026-05-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc1_roofing', '0010_financeprovider_gutteringrate_solarpartner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='detected_equipment_json',
            field=models.TextField(blank=True, default='', help_text='JSON list of equipment detected by AI feature scan (solar panels, solar HW, etc.)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='eave_lm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total eave length (lm) — drives edge protection & gutter qty', max_digits=8),
        ),
        migrations.AddField(
            model_name='quote',
            name='hip_lm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hip line length (lm)', max_digits=8),
        ),
        migrations.AddField(
            model_name='quote',
            name='perimeter_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Building perimeter (lm)', max_digits=8),
        ),
        migrations.AddField(
            model_name='quote',
            name='pitch_deg_actual',
            field=models.DecimalField(decimal_places=1, default=0, help_text='AI-measured average pitch in degrees (independent of pitch_type categorical)', max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='rake_lm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rake length (lm)', max_digits=8),
        ),
        migrations.AddField(
            model_name='quote',
            name='ridge_lm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ridge line length (lm)', max_digits=8),
        ),
        migrations.AddField(
            model_name='quote',
            name='roof_colour',
            field=models.CharField(blank=True, default='', help_text='Colorbond / tile colour (auto-detected via Geoscape when available)', max_length=60),
        ),
        migrations.AddField(
            model_name='quote',
            name='storeys',
            field=models.PositiveSmallIntegerField(default=1, help_text='Detected/declared storey count'),
        ),
        migrations.AddField(
            model_name='quote',
            name='valley_lm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valley length (lm)', max_digits=8),
        ),
    ]
