# Generated by Django 4.2.30 on 2026-05-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc1_roofing', '0011_quote_detected_equipment_json_quote_eave_lm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='markup_pct',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='Final markup applied (stored for audit + re-quote)', max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='package_tier',
            field=models.CharField(blank=True, choices=[('', '—'), ('essential', 'Essential'), ('shield', 'Shield'), ('summit', 'Summit')], default='', help_text='Package mechanism: which Good/Better/Best tier was chosen', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='pricing_mechanism',
            field=models.CharField(choices=[('cost_plus', 'Cost-Plus (Port City)'), ('tapered', 'Tapered $/m²'), ('packages', 'Good / Better / Best Packages')], default='cost_plus', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='pricing_mode',
            field=models.CharField(blank=True, default='match', help_text='Cost-Plus variant: match | optimal | premium', max_length=20),
        ),
    ]
