# Generated by Django 4.2.30 on 2026-05-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc1_roofing', '0012_quote_markup_pct_quote_package_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoofAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('address', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('zoom', models.IntegerField()),
                ('image_hash', models.CharField(help_text='SHA-256 (truncated) of the satellite PNG sent to Claude', max_length=64)),
                ('result_json', models.JSONField(help_text='Parsed Claude response (the full JSON body returned to the client)')),
                ('model_version', models.CharField(default='claude-opus-4-7', max_length=64)),
                ('prompt_version', models.CharField(default='v1', help_text='Bump in views.py to invalidate all entries when system prompt changes', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_hit_at', models.DateTimeField(auto_now=True)),
                ('hit_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Roof Analysis Cache Entry',
                'ordering': ['-last_hit_at'],
                'indexes': [models.Index(fields=['address', 'created_at'], name='uc1_roofing_address_5ae321_idx')],
            },
        ),
    ]
