# Generated by Django 4.2.30 on 2026-05-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc1_roofing', '0013_roofanalysiscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('use_measurements', 'Use measurements'), ('quote_form_submit', 'Quote form submit'), ('quote_generated', 'Quote generated')], default='use_measurements', max_length=40)),
                ('source', models.CharField(blank=True, default='', max_length=80)),
                ('address', models.TextField(blank=True, default='')),
                ('address_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total_area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('footprint_area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pitch_deg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('pitch_factor', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('eave_lm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('perimeter_m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ridge_lm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('valley_lm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hip_lm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rake_lm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('storeys', models.PositiveSmallIntegerField(default=1)),
                ('material', models.CharField(blank=True, default='', max_length=80)),
                ('roof_colour', models.CharField(blank=True, default='', max_length=80)),
                ('section_count', models.PositiveSmallIntegerField(default=0)),
                ('outline_vertices', models.PositiveSmallIntegerField(default=0)),
                ('equipment_json', models.TextField(blank=True, default='[]')),
                ('polygon_json', models.TextField(blank=True, default='[]')),
                ('sections_json', models.TextField(blank=True, default='[]')),
                ('payload_json', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_snapshots', to='uc1_roofing.quote')),
            ],
            options={
                'verbose_name': 'Measurement Snapshot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='')),
                ('address_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('pricing_mechanism', models.CharField(blank=True, default='', max_length=30)),
                ('pricing_mode', models.CharField(blank=True, default='', max_length=30)),
                ('package_tier', models.CharField(blank=True, default='', max_length=30)),
                ('roof_type', models.CharField(blank=True, default='', max_length=30)),
                ('roof_area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eave_lm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('markup_pct', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('subtotal_ex_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_inc_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inputs_json', models.TextField(blank=True, default='{}')),
                ('line_items_json', models.TextField(blank=True, default='[]')),
                ('pricing_breakdown_json', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_snapshots', to='uc1_roofing.measurementsnapshot')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_snapshots', to='uc1_roofing.quote')),
            ],
            options={
                'verbose_name': 'Quote Snapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['address_key', '-created_at'], name='qs_addr_created_idx'), models.Index(fields=['quote', '-created_at'], name='qs_quote_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeasurementUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('use_measurements', 'Use measurements'), ('measurement_apply', 'Measurement apply'), ('quote_form_submit', 'Quote form submit')], default='use_measurements', max_length=40)),
                ('address', models.TextField(blank=True, default='')),
                ('address_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('previous_total_area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_total_area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delta_area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('changed_fields_json', models.TextField(blank=True, default='[]')),
                ('payload_json', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_updates', to='uc1_roofing.quote')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='uc1_roofing.measurementsnapshot')),
            ],
            options={
                'verbose_name': 'Measurement Update',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['address_key', '-created_at'], name='mu_addr_created_idx'), models.Index(fields=['update_type', '-created_at'], name='mu_type_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='measurementsnapshot',
            index=models.Index(fields=['address_key', '-created_at'], name='ms_addr_created_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementsnapshot',
            index=models.Index(fields=['snapshot_type', '-created_at'], name='ms_type_created_idx'),
        ),
    ]
